### ISSUE TITLE
This only contains the specifications -- are there any reference implementations of this?

### ISSUE THREAD

**Issue by nathanawmk** [uport-project/specs#25]
This only contains the specifications -- are there any reference implementations of this?

Also, would like to know how uPort achieves Decentralized Identities (DIDs) ?

Nathan Aw

**Comment by rmw2** [comment]
Hi @nathanawmk, we have implementations of the specs here throughout the uport-project organization page.  In particular, [ethr-did](https://github.com/uport-project/ethr-did) is an implementation of a DID using ethereum keypairs which follows the proposed [ERC #1056](https://github.com/ethereum/EIPs/issues/1056) spec.  We also have a library to sign and verify data with DIDs, [did-jwt](https://github.com/uport-project/did-jwt).  These form the building blocks of the larger [uport identity platform](https://uport.me), which supports ethr-did among other did methods.
