### ISSUE TITLE
Clarify IPFS storage

### ISSUE THREAD

**Issue by Namenox** [uport-project/specs#60]
According to the specs, when somebody whishes to resolve my uport DID, he checks the ETHR where he finds an IPFS CID, and then he is able to retreive the DID DOC that contains my public key.

However, I see everywhere in the documentation how IPFS is treated like a magic server where data is stored for free, when in fact, in order to retrieve something from IPFS, somebody has to be hosting that document.

My question is, WHO is hosting the document containing my public key?

**Comment by mirceanis** [comment]
That question does not have a single answer. This spec does not attempt to define who the DID document holders should be. If you plan to use the `did:uport` method for your app, it's wise to also provide a pinning server to make sure your users aren't left without their DID docs.
OR
you could use the `did:ethr` method that does not rely on IPFS, and instead builds the DID document from events emitted on an ethereum network and also supports validation of signatures on-chain (without technically resolving the DID doc).

**Comment by mirceanis** [comment]
I'm going to close this. Please reopen or post a new issue if this answer does not suffice.
