### ISSUE TITLE
Uport for Quorum blokchain

### ISSUE THREAD

**Issue by Aghorb** [uport-project/specs#63]
I'm developing a donation platform based on the blockchain. I need to identify the beneficiary that can be an institution, an association, a hospital, a retirement home, a person, etc.
I study the possibility to integrate the Uport in my platform to identify the beneficiary.
So I have some questions :

1/ My platform is based on the Quorum private blockchain. So, I wonder if I can integrate Uport as an identity management solution in the Quorum network and how?

2/ In Uport, the mobile app holds the user’s keys. When a beneficiary is a person it may be logic. But When it is an organization, I cannot imagine how an organization holds its identity with a mobile. Is there any exception for an organization that replaces the use of mobile?

**Comment by mirceanis** [comment]
Thanks for asking.
1) Theoretically yes. As long as the blockchain is compatible with the ethereum virtual machine it should work.
You would probably need to deploy an [ethr-did-registry](https://github.com/uport-project/ethr-did-registry) to your chain first.

2) Institutions can use [uport-credentials](https://github.com/uport-project/uport-credentials) directly to interact with the uPort ecosystem. However there's no fully built solution I can point to as an example.

We are building a multiplatform framework to allow you to manage Decentralized Identities and Verifiable Credentials. It is designed to work for end-user apps as well as enterprises/institutions.
It is designed to be compatible with multiple identity types and use the W3C specs for Verifiable Credentials. For this reason it's not fully compatible with the existing uPort ecosystem.
Check out the development [here](https://github.com/uport-project/daf)

**Comment by Aghorb** [comment]
Thank you for reply

Can you please clarify more how can I use the uport-credentials and what is its specificity.  
If possible, can you briefly describe the workflow for this use case?

I searched somewhere and found that I could create an identity for any organization using uPort AppManager.
Is there any relation between uport-credentials and uPort AppManager?

If you can clarify these points, I will be very thankful.

**Comment by mirceanis** [comment]
[uport-credentials](https://github.com/uport-project/uport-credentials) is a library that helps create and verify credentials exchanged in the uPort ecosystem.
There is a strong relationship between AppManager and uport-credentials.
When you register an app in AppManager you get back a configuration that can be used in uport-credentials(backend library) and [uport-connect](https://github.com/uport-project/uport-connect)(frontend library)

That being said, I strongly suggest checking out [DAF](https://github.com/uport-project/daf), the framework I mentioned earlier, since that will be our main focus coming up.
The existing uPort libraries, app and infrastructure are only maintained on a best-effort basis.

**Comment by Aghorb** [comment]
Thank you again for your clarification.
One last question, is the uport-credentials permit the creation of the identity for organizations (controller and proxy contract)

**Comment by mirceanis** [comment]
It is not.
uPort has moved away from the proxy-contract model to a lightweight identity called _ethr-did_ that does not require blockchain interaction when it's created, only when updating.

This has several advantages:
 * it is much more scalable
 * easier onboarding as there is no longer a gas requirement
 * cheaper(free) to generate distinct identities to be used with distinct apps therefore increasing privacy.
 * identities are not enumerable (also a big boost to privacy)

Check out [ethr-did](https://github.com/uport-project/ethr-did), [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver) and [ethr-did-registry](https://github.com/uport-project/ethr-did-registry)
